### ISSUE TITLE
Copy operation successful but files not transferred

### ISSUE THREAD

**Issue by aanastasiou** [jeff-zucker/solid-shell#22] opened 2023-01-15 23:30 UTC
Hello

Thank you for solid-shell, I was looking for a way to copy a static website, en-masse, to my pod and the "developer-tools" list included this project which seemed to fit the bill perfectly.

Installation and invocation were pretty straightforward and copying a file (as a first level test) returned code 200. But, when I am trying to browse my `/public` folder (which is were I also set my base url to point to), the file is not there.

Any ideas as to what I may be doing wrong?

**Comment by jeff-zucker** [comment] 2023-01-16 01:28
Thanks for reporting the problem, can you tell me the OS you're operating on, the kind of server the pod is on (CSS,NSS/), and show me the exact command you used and the value of base.

**Comment by aanastasiou** [comment] 2023-01-16 13:25
The OS is Fedora Linux 35, the pod is on solidweb.org. The value of base is `https://[myusername].solidweb.org/public`.

However, at the moment, I cannot replicate the 200 message I was getting :/ (I hope this was not for operations on a local file).

In more detail, if I try to `sol -l copy ./blue.txt /blue.txt` from the command line, I am getting a 400 Bad Request.
(`blue.txt` is a file on my local file system that contains the string "Hello World".)

And if I try `sol -l put /blue.txt "Hello World"`, I am getting "400 put https://[myusername]@solidweb.org/public/blue.txt", which at least shows that the file is "located" properly with respect to the base.

While in the shell and after having called "login", I am getting a "logged in as <undefined>"....which cannot be good (?).
And again while in the shell (and loged in), I try to copy a very simple text file (which I know is right there in my public folder), using its absolute path and this one returns with 401 unauthenticated :/

**Comment by aanastasiou** [comment] 2023-02-03 12:43
@jeff-zucker any ideas about this? I hope these errors are reproducible (?)

**Comment by jeff-zucker** [comment] 2024-03-14 19:13
Closing because I can't reproduce this.

**Closed by jeff-zucker** 2024-03-14 19:13 UTC
